version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./.nginx/templates:/etc/nginx/templates
      - ./.nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./build:/usr/share/nginx/html
